name: PR-Verify

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12.x

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
