name: PR-Verify

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install git+https://github.com/linkchecker/linkchecker.git
          npm ci

      - name: Build
        run: |
          mkdocs build
