name: PR-Verify

on:
  pull_request:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12.x
      TITLE: Cloud-Native Toolkit
      ANALYTICS_ID: ""

    steps:
      - uses: actions/checkout@v2
      - name: generate site
        uses: ./.github/actions/
      - name: Set CNAME
        run: sudo chmod 777 ./public/CNAME && echo "cloudnativetoolkit.dev" > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./public

