name: Publish GitHub IO

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12.x
      TITLE: Cloud-Native Toolkit
      PATH_PREFIX: dev-guide

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: ibm-garage-cloud/dev-guide
          publish_branch: master
          publish_dir: ./public
